/icp_registration:
  ros__parameters:
    use_sim_time: false # 是否使用模拟时间，如果在真实环境中运行，应设为 false
    rough_leaf_size: 0.4 # 粗略点云下采样的叶子大小
    refine_leaf_size: 0.1 # 精细点云下采样的叶子大小
    pcd_path: "" # PCD 文件的路径，用于加载预先保存的点云地图
    map_frame_id: "map" # 地图坐标系的名称
    odom_frame_id: "odom" # 里程计坐标系的名称
    range_odom_frame_id: "lidar_odom" # 激光雷达里程计坐标系的名称
    laser_frame_id: "livox_frame" # 激光雷达坐标系的名称
    pointcloud_topic: "/livox/lidar/pointcloud" # 激光雷达点云的话题名称
    thresh: 0.05 # ICP 算法的阈值，用于判断两个点云是否对齐
    xy_offset: 0.5 # 初始位置的 XY 偏移量
    yaw_offset: 30.0 # 初始位置的偏航角偏移量
    yaw_resolution: 10.0 # 偏航角的分辨率
    initial_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # 初始位置和姿态，格式为 [x,y,z,roll,pitch,yaw]