/rc_serial_driver:
  ros__parameters:
    device_name: /dev/ttyACM0
    # device_name: /dev/ttyUSB0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

#----------------ATTENTION------------------#
# PID controller 参数顺序为 pk,pi,pd,maxI,maxOut
# desire_pose

/locdec_container:
  ros__parameters:              
    x_controller_: [1300.0, 0.0, 220.0, 0.0, 0.0]
    y_controller_: [1000.0, 0.1, 220.0, 350.0, 3000.0]
    yaw_controller_: [200.0, 5.0, 4.0, 2000.0,3000.0]
    desire_pose: [898989.0, -3.31, 90.0]
    desire_pose_1: [0.0, -3.31, 90.0]
    desire_pose_2: [0.0, -3.31, 90.0]
    desire_pose_3: [0.0, -3.31, 90.0]

/state_collector_node:
  ros__parameters:              
    #正着启动 
    # desire_pose:  [5.0, 0.0, 0.0]
    # desire_pose2: [5.0, -2.0, 0.0]
    # desire_pose3: [5.0, -2.0, 0.0]
    

    # 45度启动 红区上三区参数
    # desire_pose:  [4.15, 4.15, -45.0]
    # desire_pose2: [6.55,2.016,-45.0]
    # desire_pose3: [8.208,2.945,-45.0]

    #45度启动 蓝区上三区参数  
    #3.10 8.68  | 三区中点 ： 3.90 9.47  |
    desire_pose:  [4.25, 4.25, -45.0]
    desire_pose2: [1.60, 6.78, -45.0]
    desire_pose3: [3.97, 9.54, -45.0]
    desire_pose4: [4.97, 8.54, -45.0]
    # desire_pose3: [3.10, 8.68, -45.0]
    # 取球点
    # desire_pose4: [3.90,9.47,-45.0]

    # #这个参数是好的 
    # desire_pose2: [5.3, 3.3, -45.0]
    # desire_pose3: [5.3, 3.3, -45.0]

/controller_node:
  ros__parameters:              
    x_controller_: [1000.0, 0.0, 290.0, 450.0,300.0]
    y_controller_: [1500.0, 0.0, 250.0, 350.0,300.0]
    # yaw_controller_: [200.0, 5.0, 4.0, 3000.0,2000.0]
    # 8.208,2.945
    
    
    # 正着启动
    # desire_pose:  [5.0, 0.0,  0.0]
    # desire_pose2: [5.0, -2.0, 0.0]
    # desire_pose3: [5.0, -2.0, 0.0]

    # 45度启动 红区上三区参数
    # desire_pose:  [4.15, 4.15, -45.0]
    # desire_pose2: [6.55,2.016,-45.0]
    # desire_pose3: [8.208,2.945,-45.0]

    #45度启动 蓝区上三区参数
    desire_pose:  [4.25, 4.25, -45.0]
    desire_pose2: [1.60, 6.78, -45.0]
    desire_pose3: [3.91, 9.54, -45.0]
    desire_pose4: [5.81, 7.69, -45.0]

    #1  2.27  10.01 
    #2  2.80  10.54 
    #3  3.30  11.08
    #4  3.88  11.60
    #5  4.38  12.12

    #重试
    #1.10 -0.36
    #3.80  2.27


    # desire_pose3: [3.10, 8.68, -45.0]
    # desire_pose4: 
    #[3.90,9.47,-45.0]


    dis_thres: 0.10


# /locdec_container:
#   ros__parameters:              
#     x_controller_: [1100.0, 0.1, 270.0, 2500, 350.0]
#     y_controller_: [1000.0, 0.1, 250.0, 2200.0, 350.0]
#     yaw_controller_: [200.0, 5.0, 4.0, 3000.0,2000.0]
#     desire_pose1: [-0.8, 0.8,  90.0]
#     desire_pose2: [0.0, -3.31, 90.0]
#     desire_pose3: [0.0, -3.31, 90.0]
#     euclidisThres: 0.2