/rc_serial_driver:
  ros__parameters:
    device_name: /dev/ttyACM0
    # device_name: /dev/ttyUSB0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

#----------------ATTENTION------------------#
# PID controller 参数顺序为 pk,pi,pd,maxI,maxOut
# desire_pose

/locdec_container_node:
  ros__parameters:              
    x_controller_: [1300.0, 0.0, 220.0, 0.0, 0.0],
    y_controller_: [1000.0, 0.1, 220.0, 350.0, 3000.0]
    yaw_controller_: [200.0, 5.0, 4, 2000.0,3000.0]
    desire_pose: [0.0, -3.31, 90.0]
    desire_pose_1: [0.0, -3.31, 90.0]
    desire_pose_2: [0.0, -3.31, 90.0]
    desire_pose_3: [0.0, -3.31, 90.0]