/rc_serial_driver:
  ros__parameters:
    device_name: /dev/ttyACM0
    # device_name: /dev/ttyUSB0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

#----------------ATTENTION------------------#
# PID controller 参数顺序为 pk,pi,pd,maxI,maxOut
# desire_pose

/locdec_container:
  ros__parameters:              
    x_controller_: [1300.0, 0.0, 220.0, 0.0, 0.0]
    y_controller_: [1000.0, 0.1, 220.0, 350.0, 3000.0]
    yaw_controller_: [200.0, 5.0, 4.0, 2000.0,3000.0]
    desire_pose: [898989.0, -3.31, 90.0]
    desire_pose_1: [0.0, -3.31, 90.0]
    desire_pose_2: [0.0, -3.31, 90.0]
    desire_pose_3: [0.0, -3.31, 90.0]

/state_collector_node:
  ros__parameters:              
    #正着启动 
    # desire_pose:  [5.0, 0.0, 0.0]
    # desire_pose2: [5.0, -2.0, 0.0]
    # desire_pose3: [5.0, -2.0, 0.0]
    

    # 45度启动 红区上三区参数
    # desire_pose:  [4.15, 4.15, -45.0]
    # desire_pose2: [6.55,2.016,-45.0]
    # desire_pose3: [8.208,2.945,-45.0]

    #45度启动 蓝区上三区参数
    desire_pose:  [3.75, -3.75, 45.0]
    desire_pose2: [5.85,-1.85, 45.0]
    desire_pose3: [6.85,-2.85,45.0]

    # #这个参数是好的 
    # desire_pose2: [5.3, 3.3, -45.0]
    # desire_pose3: [5.3, 3.3, -45.0]

/controller_node:
  ros__parameters:              
    x_controller_: [1000.0, 0.0, 290.0, 450.0,500.0]
    y_controller_: [1500.0, 0.0, 250.0, 350.0,500.0]
    # yaw_controller_: [200.0, 5.0, 4.0, 3000.0,2000.0]
    # 8.208,2.945
    
    
    # 正着启动
    # desire_pose:  [5.0, 0.0,  0.0]
    # desire_pose2: [5.0, -2.0, 0.0]
    # desire_pose3: [5.0, -2.0, 0.0]

    # 45度启动 红区上三区参数
    # desire_pose:  [4.15, 4.15, -45.0]
    # desire_pose2: [6.55,2.016,-45.0]
    # desire_pose3: [8.208,2.945,-45.0]

    #45度启动 蓝区上三区参数
    desire_pose:  [3.75, -3.75, 45.0]
    desire_pose2: [5.85,-1.85, 45.0]
    desire_pose3: [6.85,-2.85,45.0]

    dis_thres: 0.50


# /locdec_container:
#   ros__parameters:              
#     x_controller_: [1100.0, 0.1, 270.0, 2500, 350.0]
#     y_controller_: [1000.0, 0.1, 250.0, 2200.0, 350.0]
#     yaw_controller_: [200.0, 5.0, 4.0, 3000.0,2000.0]
#     desire_pose1: [-0.8, 0.8,  90.0]
#     desire_pose2: [0.0, -3.31, 90.0]
#     desire_pose3: [0.0, -3.31, 90.0]
#     euclidisThres: 0.2